### ISSUE TITLE
Set of instructions

### ISSUE THREAD

**Issue by Hykire** [chaisaeng/rpi-alpine-bazel#1]
Hello Chaisaeng,

Would you mind sharing with us the code for compiling so we can see all the dependencies?

Thanks a lot!

**Comment by chaisaeng** [comment]
I did not do much just standard compilation according to the instruction outline in https://docs.bazel.build/versions/master/install-compile-source.html following is my steps
apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing build-deps cmake build-base linux-headers
download bazel-<release>.dist.zip from https://github.com/bazelbuild/bazel/releases
unzip it
export EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk"
export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
export BAZEL_JAVAC_OPTS="-J-Xms384m -J-Xmx768m"
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk"  bash ./compile.sh

Leave it to compile fore several hours on the raspberry pi (I use a pi 2B so it took very long time a pi 4 with more rams may be a lot better 

That all

**Comment by Hykire** [comment]
Thank you for your answer!
